### ISSUE TITLE
Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ardha2008** [do-web/curl-request#3]
Please help why it happend ? 

OS : Centos
NPM : 6.2.0
node : 6.11.3

```
node-libcurl WARN Could not finish postinstall
node-libcurl ERR! Error: Command failed: node "/home/apps/ardha/project/node_modules/node-libcurl/lib/Curl.js"
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/apps/ardha/project/node_modules/node-libcurl/lib/Curl.js:28:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```
Thanks

**Comment by do-web** [comment]
This has nothing to do with curl-request please ask google for this error.
